services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /home/fdekker/media/movies
        target: /media1
        read_only: true
      - type: bind
        source: /mnt/samsung/tv
        target: /media2
        read_only: true
    restart: 'unless-stopped'

  swag:
    image: linuxserver/swag
    container_name: swag-jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      URL: jellyfin-fra.nkdekker.nl
      SUBDOMAINS:
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: fdekker@gmail.com
    ports:
      - 8443:443
      - 8080:80
    volumes:
      # contains cloudflare api token in /config/dns-conf/cloudflare.ini
      # obtain api key at: https://dash.cloudflare.com/profile/api-tokens
      - /opt/swag/config:/config
    restart: 'unless-stopped'
