services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /home/fdekker/media/movies
        target: /media1
        read_only: true
      - type: bind
        source: /mnt/samsung/tv
        target: /media2
        read_only: true
    restart: 'unless-stopped'

